# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['gui.py'],
    pathex=[],
    binaries=[],
    datas=[('translations', 'translations'),
           ('docs/CREDITS_AND_DIFFERENCES.md', 'docs'),
           ('docs/ABOUT_SUPPORT_FEATURE.md', 'docs')],
    hiddenimports=[
        'tkinterdnd2',
        'pptx', 'pptx.util', 'pptx.dml.color', 'pptx.enum.text',
        'PIL', 'PIL.Image',
        'cv2', 'numpy', 'fitz',
        'translations', 'translations.translator',
        'converter', 'converter.generator', 'converter.ai_services',
        'converter.config', 'converter.cache_manager',
        'converter.image_downloader', 'converter.utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # ── Heavy packages NOT used by the application ──
        'scipy', 'scikit-image', 'skimage',
        'pandas', 'pyarrow',
        'sqlalchemy',
        'pytest', 'py', '_pytest',
        'pygments',
        'pydantic', 'pydantic_core',
        'anyio', 'sniffio',
        'dns', 'dnspython',
        'websockets',
        'fsspec',
        'bcrypt',
        'cryptography',
        'pytz', 'dateutil',
        'psycopg2',
        'jinja2', 'markupsafe',
        'setuptools', 'pkg_resources', 'distutils',
        'backports',
        'pyarrow',
        'charset_normalizer',
        'certifi',
        'urllib3',
        'matplotlib',
        'IPython', 'ipykernel', 'ipywidgets', 'jupyter',
        'notebook', 'nbconvert', 'nbformat',
        'docutils', 'sphinx',
        'test', 'tests', 'unittest',
        'streamlit',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MinerU2PPTX',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',
)
